project:
  type: website

website:
  title: "The Spatial One"
  navbar:
    right:
      - about.qmd
      - more.qmd
      - icon: github
        href: https://github.com/jrfep
      - icon: globe-americas
        href: https://jrfep.github.io
  search: true
  repo-url: https://github.com/jrfep/spatial-one
  comments:
    giscus: 
      repo: jrfep/spatial-one

format:
  html:
    theme:
      light: spacelab
      dark: darkly
    css: styles.css
    highlight-style: ayu